parameters:
#    trungnd_store.example.class: Trungnd\StoreBundle\Example

services:
#    trungnd_store.example:
#        class: %trungnd_store.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
